M48
; DRILL file {KiCad 8.0.0} date 2024-03-19T18:53:17-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-19T18:53:17-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0512
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1201
%
G90
G05
T1
X5.0756Y-2.2663
X5.5874Y-2.2701
X6.0992Y-2.2701
T2
X6.7576Y-3.2008
X6.7576Y-3.5315
M30
